// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamiza.Api.Data;

#nullable disable

namespace Tamiza.Api.Data.Migrations
{
    [DbContext(typeof(TamizaDbContext))]
    [Migration("20261003010233_AddProjects")]
    partial class AddProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tamiza")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tamiza.Api.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedApiToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_api_token");

                    b.Property<string>("EncryptedWebhookSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_webhook_secret");

                    b.Property<string>("EnumeratorField")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("enumerator_field");

                    b.Property<DateTimeOffset>("FormCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("form_checked_at");

                    b.Property<string>("FormFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_fields");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("form_name");

                    b.Property<string>("KoboAssetUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kobo_asset_uid");

                    b.Property<string>("KoboServerUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("kobo_server_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_projects_created_by");

                    b.ToTable("projects", "tamiza");
                });

            modelBuilder.Entity("Tamiza.Api.Data.ProjectInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_project_invitations");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_project_invitations_invited_by");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_project_invitations_normalized_email");

                    b.HasIndex("ProjectId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_project_invitations_project_id_normalized_email");

                    b.ToTable("project_invitations", "tamiza", t =>
                        {
                            t.HasCheckConstraint("ck_project_invitations_role", "role IN ('admin', 'analyst', 'viewer')");
                        });
                });

            modelBuilder.Entity("Tamiza.Api.Data.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", "tamiza", t =>
                        {
                            t.HasCheckConstraint("ck_project_members_role", "role IN ('admin', 'analyst', 'viewer')");
                        });
                });

            modelBuilder.Entity("Tamiza.Api.Data.SamplingFrame", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("targets");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ProjectId")
                        .HasName("pk_sampling_frames");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_sampling_frames_updated_by");

                    b.ToTable("sampling_frames", "tamiza");
                });

            modelBuilder.Entity("Tamiza.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("KeycloakSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keycloak_sub");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_sub");

                    b.ToTable("users", "tamiza");
                });

            modelBuilder.Entity("Tamiza.Api.Data.Project", b =>
                {
                    b.HasOne("Tamiza.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_created_by");
                });

            modelBuilder.Entity("Tamiza.Api.Data.ProjectInvitation", b =>
                {
                    b.HasOne("Tamiza.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_users_invited_by");

                    b.HasOne("Tamiza.Api.Data.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_projects_project_id");
                });

            modelBuilder.Entity("Tamiza.Api.Data.ProjectMember", b =>
                {
                    b.HasOne("Tamiza.Api.Data.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("Tamiza.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tamiza.Api.Data.SamplingFrame", b =>
                {
                    b.HasOne("Tamiza.Api.Data.Project", null)
                        .WithOne()
                        .HasForeignKey("Tamiza.Api.Data.SamplingFrame", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_frames_projects_project_id");

                    b.HasOne("Tamiza.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_frames_users_updated_by");
                });
#pragma warning restore 612, 618
        }
    }
}
